# Required
version: 2

# Build Environment
build:
  os: "ubuntu-20.04"

# Python configuration
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
