# Required
version: 2

# Build Environment
build:
  os: "ubuntu-20.04"
  tools: 
    python: "3.9"

sphinx:
  configuration: docs/conf.py

# Python configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
