# Required
version: 2

# Build Environment
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Python configuration
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
