[tool.poetry]
name = "marketmaps"
version = "0.1.0"
description = "A Python package for exploring markets in maps"
authors = ["Maximilian Matthe"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
numpy = ">=1.21.2"
pandas = "1.3.3"
matplotlib = "^3.5.1"
numba = "^0.55.1"
ipykernel = "^6.13.0"
scipy = "^1.8.0"
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
